[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "Cffb3HKJ5mFR6NvKP82tabnGooT4Hjc2us8LWmYqxg8L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/parrotdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
